# docker-compose.yml
# INI ADALAH FILE DOKUMEN UNTUK DOCKER-COMPOSE UNTUK DEPLOYMENT APLIKASI PYTHON FASTAPI DAN REACT
# DENGAN IMAGE YANG SUDAH DI-PUSH KE DOCKER HUB

services:
  backend:
    # Ganti bagian build ini
    # build:
    #   context: .
    #   dockerfile: ./python-fast-api-auth/Dockerfile
    image: bostang/auth-app-backend:latest # username Docker Hub dan nama repo Anda
    ports:
      - "8000:8000"
    # Volume hanya untuk development, bisa dihapus atau di-comment untuk production
    # volumes:
    #   - ./python-fast-api-auth:/app
    environment:
      # Pastikan environment variables yang diperlukan masih ada
      - DATABASE_URL=sqlite:///./sql_app.db
    restart: always

  frontend:
    # Ganti bagian build ini
    # build:
    #   context: .
    #   dockerfile: ./react-frontend-auth/Dockerfile
    image: bostang/auth-app-frontend:latest # username Docker Hub dan nama repo Anda
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always