# app-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: auth-app
type: Opaque # Tipe Secret default
data:
  # JWT Secret Key (Base64 encoded)
  JWT_SECRET_KEY: "MGExYjJjM2Q0ZTVmNmE3YjhjOWQwZTFmMmEzYjRjNWQ2ZTdmOGE5YjBjMWQyZTNmNGE1YjZjN2Q4" # Ganti dengan Base64 encoded dari JWT_SECRET_KEY Anda
  
  # Database Credentials (Base64 encoded)
  DB_USER: "cG9zdGdyZXM="         # Ganti dengan Base64 encoded dari username DB Anda
  DB_PASSWORD: "cGFzc3dvcmQ=" # Ganti dengan Base64 encoded dari password DB Anda
  DB_NAME: "cHlfYXV0aF9kYg==" # Ganti dengan Base64 encoded dari nama DB Anda



#### TUTORIAL MENDAPATKAN BASE64 ENCODED STRING ####
# Untuk mendapatkan Base64 encoded string, Anda bisa menggunakan perintah berikut di terminal:
# echo -n "your_secret_value" | base64

# Contoh:
# echo -n "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1be" | base64
# echo -n "postgres" | base64
# echo -n "password" | base64
# echo -n "py_auth_db" | base64

# output:
# MGExYjJjM2Q0ZTVmNmE3YjhjOWQwZTFmMmEzYjRjNWQ2ZTdmOGE5YjBjMWQyZTNmNGE1YjZjN2Q4
# cG9zdGdyZXM=        # untuk "postgres"
# cGFzc3dvcmQ=        # untuk "password"
# cHlfYXV0aF9kYg==    # untuk "py_auth_db" 


# atau gunakan web tools untuk encoding Base64 seperti:
# https://www.base64encode.org/