# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: auth-app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            # Mengambil POSTGRES_DB dari Secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets # Nama Secret yang kita buat
                  key: DB_NAME      # Kunci di dalam Secret yang menyimpan nama DB

            # Mengambil POSTGRES_USER dari Secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets # Nama Secret yang kita buat
                  key: DB_USER      # Kunci di dalam Secret yang menyimpan username DB

            # Mengambil POSTGRES_PASSWORD dari Secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets # Nama Secret yang kita buat
                  key: DB_PASSWORD  # Kunci di dalam Secret yang menyimpan password DB

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: auth-app
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# db-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: auth-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi